version: "3.9"

networks:
        jenkins:

services:
        blueocean:
                build:
                        context: "."
                        dockerfile: "./blueocean.Dockerfile"
                environment:
                        - DOCKER_CERT_PATH=/certs/client
                        - DOCKER_HOST=tcp://docker:2376
                        - DOCKER_TLS_VERIFY=1
                ports:
                        - "8080:8080"
                        - "50000:50000"
                volumes:
                        - jenkins-data:/var/jenkins_home
                        - jenkins-certs:/certs/client:ro
                networks:
                        - jenkins
        python-agent:
                build:
                        context: "."
                        dockerfile: "./python-agent.Dockerfile"
                environment:
                        - JENKINS_AGENT_SSH_PUBKEY
                networks:
                        jenkins:
                                aliases:
                                        - python-agent
        jenkins-docker:
                command: "--storage-driver overlay2"
                environment:
                        - DOCKER_CERT_PATH=/certs/client
                        - DOCKER_HOST=tcp://docker:2376
                        - DOCKER_TLS_CERTDIR=/certs
                        - DOCKER_TLS_VERIFY=1
                image: "docker:dind"
                networks:
                        jenkins:
                                aliases:
                                        - docker
                ports:
                        - "2376:2376"
                privileged: true
                volumes:
                        - jenkins-data:/var/jenkins_home
                        - jenkins-certs:/certs/client

volumes:
        jenkins-data:
        jenkins-certs:
