version: "3.9"

networks:
        jenkins:

services:
        blueocean:
                image: "jenkins/jenkins:lts-jdk11"
                ports:
                        - "8080:8080"
                        - "50000:50000"
                volumes:
                        - jenkins-data:/var/jenkins_home
                        - jenkins-certs:/certs/client:ro
                networks:
                        - jenkins
        python-agent:
                build:
                        context: "."
                        dockerfile: "./python-agent.Dockerfile"
                environment:
                        - JENKINS_AGENT_SSH_PUBKEY
                networks:
                        jenkins:
                                aliases:
                                        - python-agent

volumes:
        jenkins-data:
        jenkins-certs:

